format:
  html:
    theme: flatly
    indent: false
  pdf:
    latex-auto-install: false
#    latex-clean: false    # to keep artefacts incl log
    pdf-engine: latexmk
    pdf-engine-opt: -xelatex
    documentclass: scrreprt
    include-in-header: latex/unicode.tex
    mainfont: Libertinus Sans
    sansfont: Libertinus Sans
    monofont: Inconsolata
    mathfont: Libertinus Math
    babelfonts:
      greek: Libertinus Sans
