format:
  html:
    theme: flatly
    indent: false
  pdf:
    latex-auto-install: false
#    latex-clean: false    # to keep artefacts incl log
    pdf-engine: latexmk
    pdf-engine-opt: -xelatex
    documentclass: scrreprt
    include-in-header: latex/unicode.tex
    mainfont: Open Sans
    sansfont: Open Sans
    monofont: Inconsolata
    mathfont: Noto Sans Math
    babelfonts:
      greek: Open Sans
