# Dialectica template

Metadata specific to the dialectica template.

## Author Metadata

The `author` metadata field is a list, each item corresponding to 
one author. Each item has `name`, `email`, `institute` fields, and 
one author (the corresponding author) has `correspondence: true`:

```
author: 
- name: Vincent Conitzer
  email: conitzer@cs.duke.edu
  correspondence: true  
  institute: Duke University
- name: Nadine Elzein
  email: nadine.elzein@warwick.ac.uk
  institute: University of Warwick
```

If there is only one author, do include `correspondence: true` on that author.

__Multiple institutes__. Introduce multiple institutes as a comma-separated list or as a YAML list. Comma-separated list:

```
  institute: University College London, SOAS
```

YAML list:

```
  institute:
  - University College London
  - SOAS
```

__Institutes with a comma in their name__. Institutes like "University of 
California, Berkeley" have a comma in their name. To prevent the template 
from treating them as two distinct institutes, enter them as a list item:

```
  institute:
  - University of California, Berkeley
```

__Multiple short institute names__. If an author's institute include 
multiple short acronyms, e.g. "ENS, CNRS, EHESS" they will look awkward
on distinct line. Treat them as a single institute, using a list item:

```
  institute:
  - ENS, CRNS, EHESS
```

## Titles and subtitles

Longer titles may sometimes be fine-tuned in the output. We have extra title fields to do this. 

An article title's appears in four places:

1. The article's first page
2. The header (top) of right-side pages
3. If output as a single PDF ('offprint'), the PDF's cover
4. If output in an issue, the issue's table of contents

The article's subtitle appears on the first page and the offprint 
cover too. 

Here are the fields used to format titles and subtitles:

```yaml
title: Plain title here
subtitle: Plain subtitle here
shorttitle: Shorter title for page headers
title-latex: |
  Title for the first page title \
  with possibly some linebreaks
subtitle-latex: |
  Title for the first page title \
  with possibly some linebreaks
title-cover: |
  Title for the offprint cover \
  with possibly some \
  linebreaks
subtitle-cover: |
  Subtitle for the cover
title-cover-size: \huge
subtitle-cover-size: \Large
```

* `title` is mandatory
* `shortitle` is used for page headers. It should not include line breaks.
* `title-latex`, `shorttitle-latex` are used to manually set line breaks in the title and subtitle of the article's first page. These only apply to PDF output: in HTML output we don't manually set title linebreaks.
* `title-cover`, `subtitle-cover` are used to manually set line breaks on the offprint cover.
* `title-cover-size`, `subtitle-cover-size` are used to change the cover title and subtitle in PDF output. The default is `\Huge` for title and `\LARGE` for the subtitle. You should use LaTeX size commands: from larger
to smaller they are `\Huge`, `\huge`, `\LARGE`, `\Large`, `\large`, `\normalsize`.

There is no control of the first page title and subtitle font sizes. 
