---
editor: 
  markdown: 
    wrap: 72
---

# Quotations {#sec-quotations}

Quotations should only be used for quoted material: text coming from
another source. For other indented block of materials, cf
[Statements]{#cop-block-statements}.

## Inline vs block quotations

Some quotations are inline and other are blocks.

::: house
**Dialectica guidelines**. Short quotations (up to about 2 lines) are
inline, unless authors specifically want to set them out. Longer
quotations (from about 3 lines) are normally block. But they can be
inline, especially if they're basically used as a substitute for the
authors' own words rather than something to be examined or discussed.
:::

## Inline quotations

Inline quotations are encoded with quotation marks `'` or `"`. Don't use
special opening and closing quotation mark characters:

For inline quotations use single or double quotation marks:

| GOOD                              | output                          |
|-----------------------------------|---------------------------------|
| `This "best practice" is a hack.` | This "best practice" is a hack. |
| `This 'best practice' is a hack.` | This 'best practice' is a hack. |

As you can see, Pandoc automatically converts straight marks into
opening or closing ones as needed.

There are two traditions:

-   US/modern British. Double quotation marks. Closing quotation mark
    placed after punctuation marks, even if those aren't in the quote:

    > She never said the word "traitor."

-   traditional British. Single quotation marks. Closing quotation mark
    before punctuation marks unless these are parts of the quote:

    > She never said the word 'traitor'&zmj;.

Pandoc applies the US convention by default. This can be avoided
globally by setting the document's language to `en-GB`. It can be
avoided on a case-by-case basis by using a "zero-width joiner"
characters, markdown code `&zmj;`:

``` markdown
She never said the word 'traitor'&zmj;.
```

> She never said the word 'traitor'&zmj;.

::: house
**Dialectica guidelines**

*Dialectica* prefers the US/Chicago convention for quoted material, 
that is double quote. Exception: you can use single quotes for special 
uses other than quoting material (see 'mention' below). 
:::

### Quoting words (mention)

When a word or expression is used not with its usual meaning but to
denote that word or expression itself, we use quotation marks or
italics.

> I can't stand the word 'scrumptious'.

> I can't stand the word *scrumptious*.

Don't use italics if the word is scare-quoted, put a distance, quoted
from some other person's use, etc. Italics are only appropriate if we're
talking of the word or expression italicized.

::: house
**Dialectica guidelines**. If references to a word or words are common
throughout the paper, as in e.g. linguistics papers, italics are
recommended. It's often best to distinguish mention from quoted material:

- use italics or single quotation marks for mentions. Example:

  > The predicate 'gave $x$ to $y$' has three argument places.

- if using single quotation marks, do not bring punctuation marks inside. 

  > The verbs 'know', 'believe' are cognitive verbs.
  > We need another notion than 'justice'.

Scare quotes are like quoted material, not mention.

Make sure the paper is consistent in its choices.
:::

### Quotations within quotations

If you must use quotation marks within quotation marks, use different
ones:

| GOOD                       | output                   |
|----------------------------|--------------------------|
| `"This 'word' is quoted."` | "This 'word' is quoted." |
| `'This "word" is quoted.'` | 'This "word" is quoted.' |

If you try to put double quotes with double quotes, Pandoc doesn't
output them correctly.

| BAD                        | output                  |
|----------------------------|-------------------------|
| `"This "word" is quoted."` | "This"word" is quoted." |

It is best to impose the rule unless it is imperative to use the same
quotes.

If you do need to embed the same quotation marks within themselves, use
HTML entitles:

| GOOD                                  | output                  |
|---------------------------------------|-------------------------|
| `"This &ldquo;word&rdquo; is quoted"` | "This "word" is quoted" |
| `'This &lsquo;word&rsquo; is quoted'` | 'This 'word' is quoted' |

## Block quotations

Quotations are marked by either starting a paragraph with `>` and
indenting it, or by starting each line of the paragraph with `>`, or
simply having the first line starting with `>`

> This is a quotation. The second sentence is on an indented line.

> This is another quotation. The second sentence is on a line starting
> with `>`.

> This is quotation in the lazy style. The second line isn't even
> indented or starting with `>`.

``` markdown
> This is a quotation.
  The second sentence is on an indented line.
  
> This is another quotation.
> The second sentence is on a line starting with `>`.

> This is quotation in the lazy style.
The second line isn't even indented or starting with `>`.
```

For readability avoid the lazy style.

The quotation citation can be included at the end or in a footnote. If indicated at the end, it should come *after* the dot of the quotation's last sentence. 

> GOOD I am happy. [@doe_j:2020]

> BAD I am happy [@doe_j:2020].

> GOOD I am sad.[^191-cop-block-quotations-1]

[^191-cop-block-quotations-1]: @doe_j:2020

``` markdown
> GOOD I am happy. [@doe_j:2020]

> BAD I am happy [@doe_j:2020].

> GOOD I am sad.[^doe-quotation]

[^doe-quotation]: @doe_j:2020
```

Distinguish clearly *one quotation with several paragraphs*
from *several consecutive quotations*. If, for instance, your
template sets out quotations in boxes, you want a single
two-paragraphs quotation to come out in one box, not two. 
*Continuing* paragraphs are marked by an indentation of 2 spaces or by prefixing
intervening empty lines with `>`:

> Suppose this is a quotation's first paragraph.

  This second paragraph (indented) is part of the same quotation.

> Suppose this is a new quotation's first paragraph.
>
> This second paragraph (marked with `>` prefixes) 
> is part of the same quotation.

``` markdown
> Suppose this is a quotation's first paragraph.

  This second paragraph (indented) is part of the same quotation.

> Suppose this is a new quotation's first paragraph.
>
> This second paragraph (marked with `>` prefixes) 
> is part of the same quotation.
```

Beware: if you use indentation, make it two spaces only. Four spaces indentation is used for code blocks (blocks of computer language). 

*Several but consecutive* quotations are instead separated by an empty line:

> This is a first quotation.

> This is a second quotation that directly follows the first.

``` markdown
> This is a first quotation.

> This is a second quotation that directly follows the first.
```

Note that the second quotation starts with `>` and isn't indented.

You can have quotations within quotations.

> As someone said once:
>
> > The life unexamined isn't worth living.

``` markdown
> As someone said once:
> 
> > The life unexamined 
> > isn't worth living.
```

::: house
**Dialectica guidelines**

If the quote is longer than 4 lines, use block quotation.

-   no double marks
-   period goes before reference

``` markdown
> [block quotation]. [@doe_j:2020, 20]
```

Result:

> \[block quotation\]. [@doe_j:2020, 20]
:::

### Troubleshooting

*Problem*. The quotation or parts of it comes out in computer-language font. 

*Solution*. You've indented a block of your quotation by *four* spaces. Use two instead. 