# Bibliography

You should get or create a bibliography file containing the references cited
in your manuscript. This could be a BibTeX file (`.bib`) or a CSL json file 
(usually `.json`). You need to:

1. Get or create a bibliography file
2. Check whether the file includes any self-cited entries. Some bibliography 
  entries may cite other entries, so the bibliography file will cite its own 
  entries. We need to ensure that any such self-cited entry is actually present
  in the file, and we need to ensure that it is printed out in the bibliography.

*dialectica*. We use BibTeX files. The "bibliography file" below refers to a 
`.bib` file in your article's folder. 

In your article's metadata block, enter the name of your bibliography file:

```markdown
title: My paper
author: Jane E. Doe
bibliography: references.bib
```

Do not leave the bibliography field empty, or you will get a 
Pandoc error `File  not found in resource path`.

## Multiple bibliography files

You can have multiple bibliography files:

```
bibliography:
- references1.bib
- references2.bib
```

## Self-citing bibliography

**Requires**. Dialoa's recursive-citeproc filter.

A BibTeX bibliography file may 'self-cite', that is, have entries that cite other entries. Citations of other entries may appear in the `note`, `crossref` or even `title` field, for instance. 

If self-cited entries are missing from the BibTeX file, you will get 
"Citation not found" error, or you will get garbage text 
like **Smith_2008:c?** or wrong formatting like "(reprinted in (Smith 2008))" in the bibliography printed out in output formats.

If you need self-citing bibliographies, use the 
recursive-citeproc filter. Refer to its manual for details.

## Adding non-cited references in the bibliography {#sec-adding-non-cited-references-in-the-bibliography}

In the metadata block, add a line:

``` yaml
nocite: |
  @bibtexentry1, @bibtexentry2, @bibtexentry3
```

If you have lots of those, best use a tool to extract the keys
automatically from a bibtex file.

## Bibliography placement and preamble

See Pandoc user guide on how to place the bibliography in 
different parts of the body. 

### Dialectica only

(Dialectica places bibliographies with a custom filter, `bib-place`.
It's superseded by the instructions in Pandoc's user guide. The
instructions in this section are only for Dialectica copyeditors.)

The article should end with a bibliography
header:

``` markdown

# References

```

If you want to add a preamble to the bibliography, place the
header and preamble in a Div with class "refs-preamble":

``` markdown

::: {.refs-preamble}

# References {.unnumbered}

The following abbreviations are used:

* QDA: *Quaestiones disputatae de anima* [@aquinas:1953].

* SLM: *Sententia libri Metaphysicae* [@aquinas:1950].

* ST: Aquinas, *Summa Theologica* [@aquinas:1888].

All Latin editions obtained from those hosted at
    [Corpus Thomisticum](https://www.corpusthomisticum.org/), courtesy of
    the University of Navarre. [https://www.corpusthomisticum.org/](https://www.corpusthomisticum.org/)

:::

```

__Dialectica guidelines__. If using a preamble, put abbreviations
in a separate section titled 'Abbreviations', and mark both
the 'References' and 'Abbreviations' heading as unnumbered. 
See [Dialectica's bibliography guidelines](#dialectica-biblio-preamble).

## Get or create a BibTeX file

### Using Zotero

Create a new (sub)collection in your Zotero Library for the article. Add the article references to it.

Zotero creates citation keys automatically. If you need to manually change them to whichever ones you're using in the manuscript, see below.

Left-click the collection and chose "Export collection". 
Export it as BibTeX (`.bib`) file to the article's folder.

### Manually set citation keys in Zotero

Select a bibliography item. Its metadata is displayed on
the right tab. Find the 'Extra' field at the bottom. Edit
it to add a new line to whatever it may already contain:

```
Citation Key: Doe1995-Article-Title
```

This changes the item's citation key. Don't forget the caps ("Citation Key" not "citation key" nor "citationkey"), and make sure this occupies a single line of the "Extra" field.

## BibTeX file guidance

This only applies to BibTeX (`.bib`) files. If you're using CSL Json files, 
you are probably generating them from Zotero or some other bibliography
manager instead. 

### Edit BibTeX files

Several methods:

1. Edit the `.bib` file directly in a text editor. Either:

  i. fix manually what is wrong with the entry. 
  ii. delete the entry, search and add it again with the same method as 
    when you miss a reference (see below).

2. Use a BibTeX editor (BibDesk, comes with TeXshop on Macos, or JabRef).

3. Use a bibliography manager like Zotero that imports / exports BibTeX files.
  **Beware**: Zotero and others convert the `.bib` file into their own 
  formats on import. This means that you may lose of your bib file's 
  features: with Zotero, `\cite` commands (that a BibTeX file may use to 
  cite some entries in other entries) are lost.
  
### Check BibTeX file formatting

You can use `biber` (LaTeX's bibliography generator) to check 
a BibTeX file for errors. Run on the terminal:

```
biber --tool references.bib
```

This prints out a report on any problem in the file. It also
creates a cleaned-up version of the file, as 
 `references_bibtools.bib`.
 
### BibTeX field names aren't case-sensitive

BibTeX field names are not case-sensitive: they can be named "author",
or "Author", or "AUTHOR".

```bibtex
@inbook{Jakobson:1980,
  Author = {Jakobson, Roman},
  Title = {Metalanguage as a Linguistic Problem}
}
```

Is the same as:

```bibtex
@inbook{Jakobson:1980,
  author = {Jakobson, Roman},
  TITLE = {Metalanguage as a Linguistic Problem}
}
```

### Title capitalization

Traditionally, in English bibliographies titles in English are typeset in *title 
case* ("An Article with Results") but titles in other languages are typeset in
*sentence case* ("An article with results"). In German or French bibliographies,
all titles (including those of works in English) are in sentence case.^[The 
Chicago manual recommends title case for English titles; the APA manual 
recommends sentence case for all titles.]

The appearance is controlled by our bibliography template. For this to work
entries in the the BibTeX file must:

1. Have a `langid` field specifying the entry's language 
  as an [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag): 
  `en`, `en-US`, `de`, etc.^[The [polyglossia package 
  documentation](https://www.ctan.org/pkg/polyglossia) has a useful
  list of tags. If you have a full LaTeX installation you can also get it from 
  the terminal by running the command `texdoc polyglossia`.] Though (at least 
  some) full names like `english` or `french` will work too. If there is no  
  `langid` field for a given BibTeX entry,  the entry is assumed to 
  be in the language of the  document (as specified in the document's metadata, 
   `lang` field).
2. Have titles in *sentence case*, that is, where only names and words that need
  to be capitalized no matter what are in upper case. For instance, "The 
  philosophy of logical atomism" or "Der Wahrheitsbegriff in den 
  formalisierten Sprachen". 

If an entry uses title case ("Rezension der Schrift von..."), the 
capitals will be assumed to be mandatory and will be printed even
when it should be in sentence case. Thus if you know that your bibliography
entries in English will always be printed in title case (i.e., your publication
is in English and you're sure it won't adopt the APA sentence case convention),
then it's harmless to use title case in the BibTeX file itself. But when in 
doubt sentence case + `langid` field is the safe option. 

For an illustration: 

```bibtex
@article{Tarski1936,
	author = {Alfred Tarski},
	title = {Der Wahrheitsbegriff in den formalisierten Sprachen},
	journal = {Studia Philosophica},
	volume = {1},
	pages = {261--405},
	year = {1936},
	langid = {de},
}
@article{Russell1905,
	author = {Bertrand Russell},
	title = {On denoting},
	journal = {Mind},
	volume = {14},
	number = {56},
	pages = {479--493},
	year = {1905},
  langid = {en},
}

```

For more detail:

* the `langid` field is a [`biblatex` field 
  name](https://www.ctan.org/pkg/biblatex). It is recognized by Pandoc's 
  `citeproc` (Pandoc's internal citation processor) for use in a association 
  with a CSL style file. 
* There is a `language` field in BibTeX files too. But it is not meant to affect
  an entry's format; rather, it is used for entries to explicitly
  state its language](ttps://tex.stackexchange.com/questions/323441/how-does-langid-field-in-biblatex-differ-from-language-field)
  affect the formal of the bibliography.

### Original year of publication

If the author isn't using the original edition of a book, e.g. citing
from a 2010 edition of Locke's 1689 essay, add a field origdate in the
bibtex entry. (will not show up in the PDF at the moment, but our final template
will do it). Ex:

```bibtex
@inbook{Jakobson:1980,
  Author = {Jakobson, Roman},
  Booktitle = {The Framework of Language},
  Location = {Ann Arbor},
  Year = {1980}
  Origdate = {1956},
  Pages = {81\--92},
  Publisher = {University of Michigan Press},
  Shorttitle = {Metalanguage as a Linguistic Problem},
  Title = {Metalanguage as a Linguistic Problem}
}
```

See [biblatex documentation, §2.2.2 on data
fields](http://texdoc.net/texmf-dist/doc/latex/biblatex/biblatex.pdf).

### BibTeX conventions and resources

There are two BibTeX standards that can be used:

* BibTeX
* BibLaTeX

The two conventions overlap a lot (most of the field names are common).
The BibLaTeX conventions are more recent and complete. The BibTeX ones are 
widely used, and almost entirely compatible with BibLaTeX. 
Each corresponds to a LaTeX bibliography processor (`bibtex` and `biber`, 
respectively). Both are understood by Pandoc's bibliography processor, `citeproc`. 

Where to find references on these BibTeX standards?

1. BibTeX. The [BibTeX original documentation](https://www.ctan.org/pkg/bibtex) (1988), Paperpile's [BibTeX guide](https://www.bibtex.com/format/).
2. BibLaTeX. The [BibLaTeX official documentation](https://www.ctan.org/pkg/biblatex) and the 
[BibLaTeX cheatsheet](https://www.ctan.org/pkg/biblatex-cheatsheet).

Note: if you have a full LaTeX installation on your computer you will have 
access to some of these documents from your terminal using the `texdoc` 
command. Try the commands:

```bash
texdoc biblatex

texdoc biblatex-cheatsheet

texdoc bibtex
```

**Dialectica guideline**. We use the `biblatex` conventions. 

### BibTeX file special entry types

#### Unpublished manuscript

Choose the type `unpublished`. Add a note field:

```bibtex
  note = {unpublished manuscript}
```

Add a URL if available.

*Dialectica guideline*. We require a URL. If the author cannot provide a URL, we
do not create a bibliography entry at all but only describe the source in a 
footnote ("in an unpublished manuscript titled "XXX").

## Troubleshooting and examples

### Error message: Unexpected end of file

The following message indicates an error with the BibTeX file:

```
Error at "percent.bib" (line 9, column 1):
unexpected end of input
```

### Percent signs in DOI field

At the moment % signs in DOI fields generate an error. 

If you copied/pasted DOIs in your BibTeX file, symbols in 
them may end up 'percent-encoded', e.g. "%2F" instead of "/".
For instance, the DOI "10.1007/15.12345" copied from
the web may end up being pasted as "10.1007%2F15.12345".

These DOIs crash Pandoc version 3.0.1 and lower, but the
bug will be fixed in future releases.


### Error message: `\citet` unknown command

**Requires:** script or filter that manages recursive bibliography management .

Pandoc encounters a LaTeX citation command (`\citet` or the like). Unless you
or the author has written one in the text, it is in the .bib file.^[Explanation.
By default Pandoc doesn't process the `\citet` command in a bib file (at least, not if 
the field is "title", and perhaps not in general), leaves the `\citet` command.
At the LaTeX stage it's not recognized by LaTeX (because we don't load natbib).]

Solution 1. In Dialectica, LaTeX citation commands in the .bib file are processed. This is achieved by a script that runs pandoc on the document twice,
first to generate a json that includes the biblio, second to generate the final 
output (at which state the latex commands in the biblio are processed). The
first run is `--to json` and the second with `-M suppress-bibliography`. 
Suggested by John MacFarlane on pandoc-discuss. 

Solution 1. Replace the offending `\citet` command(s) in your .bib file. To find it or them:

* process the markdown with .tex output.
* search \\citet in the tex output. you should see which bib entry it is in.
* go to the .bib file and replace the `\citet{jones_a:2020}` in that entry with e.g. `Jones (2020)`, and in the md, enter the citation key as no-cite (see above)

Solution 2. Implement a double-pass generation procedure. This is the publisher's
job.

::: private
We have now figured out a method to process those command. However, we'll need
to update the document-generation procedure to implement it. Either wait for it,
or use solution 1.

in a field of your .bib file is printed out. It needs to be replaced. To find it:

* process the markdown with .tex output.
* search \\citet in the tex output. you should see which bib entry it is in.
* go to the .bib file and replace the `\citet{jones_a:2020}` in that entry with e.g. `Jones (2020)`, and in the md, enter the citation key as no-cite (see above)

Explanation. Pandoc doesn't process it (at least, not if the field is "title", and perhaps not in general), leaves the `\citet` command. At the LaTeX stage it's not recognized by LaTeX (because we don't load natbib).

:::

### From Frege to gödel

Mystery. The cross ref below is printed out as "From Frege to gödel: "
by citeproc, no matter (a) whether we write `Gödel` or `G{\¨o}del`, (b) no
matter the position, i.e. we get "From gödel to Frege". **The solution
is** put G in curly brackets. But why???

```bibtex
\@incollection{frege:1967a,
  Author = {Frege, Gottlob},
  Crossref = {vanheijenoort:1967},
  Note = {translated by Stephan Bauer-Mengelberg},
  Num_Sort = {40337},
  Pages = {1\--82},
  Title = {Begriffsschrift: A Formula Language Modeled on that of
  Arithmetic, for Pure Thought},
  Year = {1967}
}

\@book{vanheijenoort:1967,
  editor = {van Heijenoort, Jan},
  year = {1967},
  title = {From Frege to G{\"o}del: A Source Book in Mathematical Logic
  1879-1931},
  booktitle = {From Frege to {G}ödel: A Source Book in Mathematical Logic
  1879-1931},
  address = {Cambridge, Massachusetts},publisher = {Harvard University
  Press}
}
```

Beginning of an answer: case is protected if a *subpart* of the word is bracketed. `A dog called {Pizza}` will be overriding by the style (and thus printed "A pizza" if the style calls for it) but `A dog called {P}izza` is 
protected.

